version: '3.8'

services:
   pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    command: >
      bin/pulsar standalone
    ports:
      - "6650:6650"   # Pulsar binary protocol port
      - "8080:8080"   # Pulsar HTTP service port
    environment:
      PULSAR_MEM: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m"
    volumes:
      - pulsar_data:/pulsar/data
      - pulsar_conf:/pulsar/conf
    networks:
      - pulsar_network    
      
   pulsar-manager:
    image: "apachepulsar/pulsar-manager:v0.4.0"
    container_name: pulsar-manager
    ports:
      - "9527:9527"
      - "7750:7750"
    depends_on:
      - pulsar
    links:
      - pulsar     
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
      LOG_LEVEL: DEBUG
      SERVER_PORT: 7750 
      
    networks:
      - pulsar_network   


volumes:
  pulsar_data:
  pulsar_conf:
  
networks:
  pulsar_network:
    name: pulsar_network
    driver: bridge    
