server:
  port: 8082


spring:
  pulsar:
    client:
      operation-timeout: 30m
      service-url: pulsar://127.0.0.1:6650
    consumer:
      name: notification_sender
      topics:
        - notification-topic

